// <auto-generated />
namespace MusicRaterWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial_review_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_review_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201808052046019_initial_review_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
